2023-03-09 17:01:47,598 INFO    Thread-28 (process_request_thread):12328 [wandb_setup.py:_flush():68] Configure stats pid to 12328
2023-03-09 17:01:47,598 INFO    Thread-28 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from C:\Users\beaconproduction\.config\wandb\settings
2023-03-09 17:01:47,598 INFO    Thread-28 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\settings
2023-03-09 17:01:47,598 INFO    Thread-28 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-09 17:01:47,598 WARNING Thread-28 (process_request_thread):12328 [wandb_setup.py:_flush():68] Could not find program at -m __main__
2023-03-09 17:01:47,598 INFO    Thread-28 (process_request_thread):12328 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m __main__'}
2023-03-09 17:01:47,598 INFO    Thread-28 (process_request_thread):12328 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\run-20230309_170147-ojwpk7fh\logs\debug.log
2023-03-09 17:01:47,598 INFO    Thread-28 (process_request_thread):12328 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\run-20230309_170147-ojwpk7fh\logs\debug-internal.log
2023-03-09 17:01:47,598 INFO    Thread-28 (process_request_thread):12328 [wandb_init.py:init():532] calling init triggers
2023-03-09 17:01:47,598 INFO    Thread-28 (process_request_thread):12328 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-09 17:01:47,598 INFO    Thread-28 (process_request_thread):12328 [wandb_init.py:init():583] wandb.init() called when a run is still active
2023-03-09 17:01:47,811 INFO    Thread-28 (process_request_thread):12328 [wandb_run.py:_finish():1854] finishing run heywire/HeywireAI/q8tqaahu
2023-03-09 17:02:16,763 INFO    Thread-31 (process_request_thread):12328 [wandb_setup.py:_flush():68] Configure stats pid to 12328
2023-03-09 17:02:16,763 INFO    Thread-31 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from C:\Users\beaconproduction\.config\wandb\settings
2023-03-09 17:02:16,763 INFO    Thread-31 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\settings
2023-03-09 17:02:16,763 INFO    Thread-31 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-09 17:02:16,763 WARNING Thread-31 (process_request_thread):12328 [wandb_setup.py:_flush():68] Could not find program at -m __main__
2023-03-09 17:02:16,763 INFO    Thread-31 (process_request_thread):12328 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m __main__'}
2023-03-09 17:02:16,763 INFO    Thread-31 (process_request_thread):12328 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\run-20230309_170216-ictnj00u\logs\debug.log
2023-03-09 17:02:16,779 INFO    Thread-31 (process_request_thread):12328 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\run-20230309_170216-ictnj00u\logs\debug-internal.log
2023-03-09 17:02:16,779 INFO    Thread-31 (process_request_thread):12328 [wandb_init.py:init():532] calling init triggers
2023-03-09 17:02:16,779 INFO    Thread-31 (process_request_thread):12328 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-09 17:02:16,779 INFO    Thread-31 (process_request_thread):12328 [wandb_init.py:init():588] starting backend
2023-03-09 17:02:16,779 INFO    Thread-31 (process_request_thread):12328 [wandb_init.py:init():592] setting up manager
2023-03-09 17:02:16,779 INFO    Thread-31 (process_request_thread):12328 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-09 17:02:16,795 INFO    Thread-31 (process_request_thread):12328 [wandb_init.py:init():599] backend started and connected
2023-03-09 17:02:16,795 INFO    Thread-31 (process_request_thread):12328 [wandb_init.py:init():687] updated telemetry
2023-03-09 17:02:16,888 INFO    Thread-31 (process_request_thread):12328 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [wandb_setup.py:_flush():68] Configure stats pid to 12328
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from C:\Users\beaconproduction\.config\wandb\settings
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\settings
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-09 17:02:27,971 WARNING Thread-35 (process_request_thread):12328 [wandb_setup.py:_flush():68] Could not find program at -m __main__
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m __main__'}
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\run-20230309_170227-a3y30n4h\logs\debug.log
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\run-20230309_170227-a3y30n4h\logs\debug-internal.log
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [wandb_init.py:init():532] calling init triggers
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [wandb_init.py:init():588] starting backend
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [wandb_init.py:init():592] setting up manager
2023-03-09 17:02:27,971 INFO    Thread-35 (process_request_thread):12328 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-09 17:02:27,986 INFO    Thread-35 (process_request_thread):12328 [wandb_init.py:init():599] backend started and connected
2023-03-09 17:02:27,986 INFO    Thread-35 (process_request_thread):12328 [wandb_init.py:init():687] updated telemetry
2023-03-09 17:02:28,080 INFO    Thread-35 (process_request_thread):12328 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-09 17:02:57,777 INFO    Thread-39 (process_request_thread):12328 [wandb_setup.py:_flush():68] Configure stats pid to 12328
2023-03-09 17:02:57,777 INFO    Thread-39 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from C:\Users\beaconproduction\.config\wandb\settings
2023-03-09 17:02:57,777 INFO    Thread-39 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\settings
2023-03-09 17:02:57,777 INFO    Thread-39 (process_request_thread):12328 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-09 17:02:57,777 WARNING Thread-39 (process_request_thread):12328 [wandb_setup.py:_flush():68] Could not find program at -m __main__
2023-03-09 17:02:57,777 INFO    Thread-39 (process_request_thread):12328 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m __main__'}
2023-03-09 17:02:57,777 INFO    Thread-39 (process_request_thread):12328 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\run-20230309_170257-hebd6r5d\logs\debug.log
2023-03-09 17:02:57,777 INFO    Thread-39 (process_request_thread):12328 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\beaconproduction\sites\local\python\heywire\openai\wandb\run-20230309_170257-hebd6r5d\logs\debug-internal.log
2023-03-09 17:02:57,777 INFO    Thread-39 (process_request_thread):12328 [wandb_init.py:init():532] calling init triggers
2023-03-09 17:02:57,777 INFO    Thread-39 (process_request_thread):12328 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-09 17:02:57,777 INFO    Thread-39 (process_request_thread):12328 [wandb_init.py:init():588] starting backend
2023-03-09 17:02:57,777 INFO    Thread-39 (process_request_thread):12328 [wandb_init.py:init():592] setting up manager
2023-03-09 17:02:57,793 INFO    Thread-39 (process_request_thread):12328 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-09 17:02:57,793 INFO    Thread-39 (process_request_thread):12328 [wandb_init.py:init():599] backend started and connected
2023-03-09 17:02:57,809 INFO    Thread-39 (process_request_thread):12328 [wandb_init.py:init():687] updated telemetry
2023-03-09 17:02:57,892 INFO    Thread-39 (process_request_thread):12328 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-09 17:03:17,242 ERROR   Thread-31 (process_request_thread):12328 [wandb_init.py:init():741] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-03-09 17:03:17,391 ERROR   Thread-31 (process_request_thread):12328 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "C:\Users\beaconproduction\sites\local\python\heywire\openai\venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\beaconproduction\sites\local\python\heywire\openai\venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 759, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
